### ISSUE TITLE
initAudio just segfaults

### ISSUE THREAD

**Issue by locallycompact** [csabahruska/proteaaudio#1]
Hi, using the initAudio call simply segfaults for me

```
Prelude> import Sound.ProteaAudio              
Prelude Sound.ProteaAudio>  initAudio 64 44100 1024
/tmp/nix-shell-22659-0/rc: line 1: 23749 Segmentation fault      '/nix/store/g8mbp29sl24xp0ap8l7zbq9ih1ydqiil-stack-1.9.3/bin/stack' $STACK_IN_NIX_EXTRA_ARGS '--internal-re-exec-version=1.9.3' 'ghci'
```

**Comment by csabahruska** [comment]
What is the underlying audio system?
It should be PulseAudio.
It works on my system (Ubuntu 16.04).

**Comment by csabahruska** [comment]
Which version do you use of proteaaudio?

**Comment by locallycompact** [comment]
Hi, yes it is pulseaudio. Using latest head of proteaaudio.

**Comment by csabahruska** [comment]
I see.
What is your operating system?

**Comment by locallycompact** [comment]
Yes NixOS

pulseaudio works fine otherwise, failed both compiled and in ghci

**Comment by locallycompact** [comment]
Fixed, closing

**Comment by csabahruska** [comment]
fixed in PR: https://github.com/csabahruska/proteaaudio/pull/2
