### ISSUE TITLE
Possibility to pause playing sounds

### ISSUE THREAD

**Issue by PlanetTeamSpeakk** [csabahruska/proteaaudio#16]
I may be mistaken, but it seems to me like there is no possibility to pause sounds that are currently playing. The only option you have is to stop it altogether, but I'd like to be able to resume it later. My use case is pausing playing sounds in my game when the game is paused.
Would be great if this could be added! Pretty much the only thing I feel like this library is missing.

**Comment by csabahruska** [comment]
Hi, would this solve your issue?
aae6c29ff33659487cdda78007622aaca18bb1aa

**Comment by PlanetTeamSpeakk** [comment]
Seems like it, let me try it out.

**Comment by csabahruska** [comment]
Released [proteaaudio-0.10.1](https://hackage.haskell.org/package/proteaaudio-0.10.1) with pause support.
