### ISSUE TITLE
Unable to build with GHC 8.10

### ISSUE THREAD

**Issue by mgmeier** [csabahruska/proteaaudio#6]
Currently, it is impossible to pass flags to the C++ compiler, since GHC 8.10 will use only -optcxx for that, whereas before, -optc would suffice.
Cabal however does currently not evaluate the `cxx-sources` and `cxx-options` fields correctly. This means, the necessary flags will never pass from cabal-install > ghc > gcc / clang / ...

This issue is blocked by: https://github.com/haskell/cabal/issues/6421

**Comment by csabahruska** [comment]
The cabal issue is fixed not.
So proteaaudio now should compile with GHC 8.10 also.
fixed in: https://github.com/csabahruska/proteaaudio/commit/3344a673493757114c30a2b56aa59d2cdcea446e
