### ISSUE TITLE
A way to check if a sound is still active.

### ISSUE THREAD

**Issue by ChristopherKing42** [csabahruska/proteaaudio#7]
I notice that there is a function that gives the number of active sounds. I suggest adding a function of type `Sound -> IO Bool` that tells you if a given sound is still active. Or a function that tells you what the remaining duration is would work too!

**Comment by csabahruska** [comment]
OK,
I've implemented it in this commit: https://github.com/csabahruska/proteaaudio/commit/022165069dd92ba2ab410d7bd2b124449ba19c0b

renamed: `soundActive :: IO Int ` to `soundActiveAll`  
added: `soundActive :: Sound -> IO Bool`

**Comment by ChristopherKing42** [comment]
Exactly what I was thinking, thank you!
